<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <_VersionFile>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</_VersionFile>
    <Version>$(_VersionFile)</Version>
  </PropertyGroup>

  <PropertyGroup>
    <PackageProjectUrl>https://github.com/gabrieloliveirabrito/envsettings</PackageProjectUrl>
    <RepositoryUrl>https://github.com/gabrieloliveirabrito/envsettings</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
